"""Interaction planning and single-target execution contracts."""

from .comment_flow import (
    COMMENT_FLOW_SMOKE_CONFIRMATION,
    CommentFlowContractError,
    CommentFlowGate,
    CommentFlowResult,
    CommentInteractionPlan,
    CommentSnapshot,
    CommentTarget,
    execute_single_comment_flow,
)
from .runtime import CommentActionStore
from .planning import (
    ApprovedCommentPlan,
    ApprovedPlanError,
    MessageApproval,
    build_approved_comment_plan,
)
from .approval import (
    APPROVAL_RECORD_CONFIRMATION,
    MessageApprovalStore,
    approval_hash,
)
from .note_comment_flow import (
    NOTE_COMMENT_CONFIRMATION, NoteCommentError, NoteCommentPlan,
    NoteCommentGate, NoteCommentResult, NoteCommentStore, execute_note_comment,
    note_context_hash,
)
from .session import (
    CURRENT_PAGE_EXECUTION_CONFIRMATION,
    CURRENT_PAGE_APPROVAL_CONFIRMATION,
    CurrentPageExecutionResult,
    CurrentPageInteractionPlan,
    InteractionBranch,
    InteractionSessionError,
    InteractionSessionStore,
    adopt_readonly_search_session,
    execute_current_page_plan,
    prepare_readonly_search_session,
)
from .compiler import (
    COMPILER_VERSION,
    NOTE_COMMENT_COMPILER_VERSION,
    COMMENT_LIKE_COMPILER_VERSION,
    NOTE_LIKE_COMPILER_VERSION,
    CompiledCurrentPagePlan,
    CompiledPlanStore,
    NoteCommentApproval,
    NoteLikeApproval,
    compile_approved_note_like_plan,
    compile_approved_note_comment_plan,
    compile_comment_like_plan,
    compile_approved_reply_plan,
)

__all__ = [
    "CommentFlowContractError",
    "COMMENT_FLOW_SMOKE_CONFIRMATION",
    "CommentFlowGate",
    "CommentFlowResult",
    "CommentInteractionPlan",
    "CommentSnapshot",
    "CommentTarget",
    "execute_single_comment_flow",
    "CommentActionStore",
    "ApprovedCommentPlan",
    "ApprovedPlanError",
    "MessageApproval",
    "build_approved_comment_plan",
    "APPROVAL_RECORD_CONFIRMATION",
    "MessageApprovalStore",
    "approval_hash",
    "NOTE_COMMENT_CONFIRMATION", "NoteCommentError", "NoteCommentPlan",
    "NoteCommentGate", "NoteCommentResult", "NoteCommentStore",
    "execute_note_comment", "note_context_hash",
    "CurrentPageExecutionResult", "CurrentPageInteractionPlan",
    "InteractionBranch", "InteractionSessionError", "InteractionSessionStore",
    "execute_current_page_plan",
    "adopt_readonly_search_session",
    "prepare_readonly_search_session",
    "CURRENT_PAGE_EXECUTION_CONFIRMATION",
    "CURRENT_PAGE_APPROVAL_CONFIRMATION",
    "COMPILER_VERSION",
    "NOTE_COMMENT_COMPILER_VERSION",
    "COMMENT_LIKE_COMPILER_VERSION",
    "NOTE_LIKE_COMPILER_VERSION",
    "CompiledCurrentPagePlan",
    "CompiledPlanStore",
    "NoteCommentApproval",
    "NoteLikeApproval",
    "compile_approved_note_like_plan",
    "compile_approved_note_comment_plan",
    "compile_comment_like_plan",
    "compile_approved_reply_plan",
]
